# Generated by Django 5.1.6 on 2025-02-12 06:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='students/photos/'),
            preserve_default=False,
        ),
    ]
