# Generated by Django 5.1.6 on 2025-02-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='author',
        ),
    ]
