# Generated by Django 5.1.4 on 2025-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='students/photos/'),
        ),
    ]
