# Generated by Django 5.1.6 on 2025-02-14 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0006_remove_department_author'),
        ('students', '0005_alter_student_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='departments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='departments.department'),
        ),
    ]
