# Generated by Django 5.1.6 on 2025-02-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='author',
        ),
    ]
