# Generated by Django 5.1.6 on 2025-02-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='grade_level',
            field=models.CharField(choices=[('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('grade_6', 'Grade 6'), ('grade_7', 'Grade 7'), ('grade_8', 'Grade 8'), ('grade_9', 'Grade 9'), ('grade_10', 'Grade 10'), ('grade_11', 'Grade 11'), ('grade_12', 'Grade 12')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teachers',
        ),
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='subjects', to='teachers.teacher'),
        ),
    ]
