# Generated by Django 5.1.6 on 2025-02-12 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subject_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
    ]
