# Generated by Django 5.1.6 on 2025-02-11 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_headofdepartment_remove_department_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='department',
            name='contact_phone',
            field=models.CharField(default=998901234567, max_length=15),
            preserve_default=False,
        ),
    ]
