# Generated by Django 5.1.6 on 2025-02-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_rename_descriptions_department_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headofdepartment',
            name='full_name',
            field=models.CharField(choices=[('John Smith', 'John Smith'), ('Alice Johnson', 'Alice Johnson'), ('Robert Brown', 'Robert Brown'), ('Emma Davis', 'Emma Davis'), ('Michael Wilson', 'Michael Wilson'), ('Sarah Taylor', 'Sarah Taylor'), ('David Martinez', 'David Martinez'), ('Olivia Anderson', 'Olivia Anderson'), ('James Thomas', 'James Thomas'), ('Laura White', 'Laura White')], max_length=100, unique=True),
        ),
    ]
