# Generated by Django 5.1.6 on 2025-02-12 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0005_department_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='author',
        ),
    ]
